my_django/mangodjango/blogApp/urls.py
from django.urls import path
from .models import Post
from django.views.generic import ListView, DetailView

urlpatterns = [
    
    path('', ListView.as_view(
        
        queryset= Post.objects.all().order_by('-date')[:25],
        template_name='blog.html'
    )),
    
    path('<int:pk>/', DetailView.as_view(
        model=Post,
        template_name='post.html'
    )),
]

my_django/mangodjango/mangodjango/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('still/', include('stillApp.urls')),
    path('blog/', include('blogApp.urls')),
    path('polls/', include('polls.urls')), 
    path('user_auth/', include('django.contrib.auth.urls')),
    path('user_auth/', include('user_auth.urls')),
]

my_django/mangodjango/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/result/', views.results, name='result'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

my_django/mangodjango/stillApp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    
    path('', views.index_view, name='index'),
    path('welcome/', views.welcome_view, name='welcome')
    
]

my_django/mangodjango/user_auth/urls.py
from django.urls import path
from . import views

app_name = 'user_auth'

urlpatterns = [
    
    path('', views.user_login, name='login'),
    path('authenticate_user/', views.authenticate_user, 
         name='authenticate_user'),
]

my_django/mangodjango/blogApp/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=200)
    body = models.TextField()
    signature = models.CharField(max_length=50, default="keep on rockin'")
    date = models.DateTimeField()
    
def __str__(self):
    return f'{self.title}'

my_django/mangodjango/polls/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    
    question_text = models.CharField(max_length=200)
    publish_date = models.DateTimeField('date published')
    
class Choice(models.Model):
    
    question = models.ForeignKey(Question, models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
def __str__(self):
    return f"{Question.question_text}, {Choice.choice_text}"

my_django/mangodjango/stillApp/models.py
from django.db import models

# Create your models here.

my_django/mangodjango/user_auth/models.py
from django.db import models

# Create your models here.

my_django/mangodjango/blogApp/views.py
from django.shortcuts import render

# Create your views here.

my_django/mangodjango/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import Question,Choice


# Create your views here
def index(request):
    latest_question_list = Question.objects.order_by('-publish_date')[:5]
    context = {'latest_question_list':latest_question_list}
    
    return render(request, 'poll.html', context)

def poll(request):
    return HttpResponse("Welcome to the polls index!")

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    
    return render(request, 'detail.html', {'question':question})
    
def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'results.html', {'question': question})
    
def vote(request, question_id):
    
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(
    pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
# Redisplay the question voting form
        return render(request, 'detail.html', {
            'question': question,
            'error_message': "You didn't select a choice."
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
# Always return an HttpResponseRedirect after successfully
# dealing with POST data. This prevents data from being
# posted twice if a
# user hits the Back button.
        return HttpResponseRedirect(reverse('polls:result', args=(question_id,)))

my_django/mangodjango/stillApp/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index_view(request):
    
    return HttpResponse("Hi there, you've landed on the stillApp index page.")


def welcome_view(request):
    
    return render(request, 'hello.html')

my_django/mangodjango/user_auth/views.py
from django.shortcuts import render, HttpResponseRedirect, reverse
from django.contrib.auth import authenticate, login

# Create your views here.
def user_login(request):
    return render(request, 'authentication/login.html')

def authenticate_user(request):
    
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    
    if user is None:
        return HttpResponseRedirect(reverse('user_auth:login'))
    
    else:
        login(request, user)
        return HttpResponseRedirect(reverse('user_auth:show_user'))

my_django/mangodjango/blogApp/templates/blog.html
{% block content %}

    {% for post in object_list %}
        <h5>{{post.date|date:"Y-m-d"}}
            <a href='/blog/{{post.id}}'> {{post.title}}</a></h5>

    {% endfor %}
{% endblock %}

my_django/mangodjango/blogApp/templates/post.html
{% block content %}

    <h3><a href="/blog/{{post.id}}">{{post.title}}</a></h3>

    <h6>on {{post.date}}</h6>

    <div class='container'>

        {{post.body|safe|linebreaks}}
        {{post.signature|safe|linebreaks}}

    </div>
    <br><br>

{% endblock %}

my_django/mangodjango/polls/templates/detail.html
<h1> {{question.question_text}}</h1>

    {% if error_message %}
        <p><strong>{{error_message}}</strong></p>
    {% endif %}

    <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice {{
                forloop.counter}}" value="{{ choice.id }}" />
            <label for="choice {{ forloop.counter }}">
            {{ choice.choice_text }}
            </label>
            <br />
        {% endfor %}
        
        <input type="submit" value="Vote" />

    </form>

my_django/mangodjango/polls/templates/poll.html
{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
        <li>
            <a href = "{% url 'polls:detail' question.id %}">
            {{ question.question_text }}
            </a>
        </li>
        {% endfor %}
    </ul>

{% else %}

    <p>No polls are available.</p>
    
{% endif %}

my_django/mangodjango/polls/templates/results.html
<h1> {{ question.question_text }} </h1>
    <ul>
        {% for choice in question.choice_set.all %}
        <li>
            {{ choice.choice_text }} -- {{ choice.votes}}
            vote{{choice.votes|pluralize}}
        </li>
        {% endfor %}
    </ul>

    <a href="{% url 'polls:detail' question.id %}">
        Vote again?
    </a>

my_django/mangodjango/stillApp/templates/hello.html
<!DOCTYPE html>
<html lang='en'>

    <head> 
        <meta charset='UTF-8'>
        <title>Welcome</title>
    </head>

    <body>
        <h1>Welcome to the app main page!</h1>

        <br>
        
        <p>nightmarenightmarenightmarenightmarenightmare</p>
        <p>nightmarenightmarenightmarenightmarenightmare</p>

    </body>

</html>

my_django/mangodjango/user_auth/templates/authentication/login.html
<h1> Login as User </h1>
    <form action="{% url 'user_auth:authenticate_user' %}" method="post">
    {% csrf_token %}
        <label>Username</label>
        <input type="text" name="username" placeholder="User" required>
    <br/><br/>
    <label>Password</label>
        <input type="password" name="password" required>
    <br/><br/>
    <input type="submit" value="Login" />
</form>

my_django/mangodjango/user_auth/templates/authentication/user.html
<h1> Welcome, {{username}} </h1>

<p> Your password is {{password}}</p>